apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: {{ .Chart.Name }}
    environment: {{ .Values.metadata.labels.environment }}

spec:
  type: {{ .Values.service.type }}
  ports:
      - port: 9000
        targetPort: 9000
        name: '9000'
  selector:
    app: {{ .Chart.Name }}
    environment: {{ .Values.metadata.labels.environment }}
