apiVersion: v1
kind: Service
metadata:
  name: { { .Chart.Name } }
  labels:
    app: { { .Chart.Name } }
    environment: { { .Values.metadata.labels.environment } }

spec:
  type: { { .Values.service.type } }
  selector:
    app: { { .Chart.Name } }
    environment: { { .Values.metadata.labels.environment } }
