replicaCount: 1

metadata:
  labels:
    environment: dev

config:
  MYSQL_USER: crater

secrets:
  MYSQL_PASSWORD: ''
  MYSQL_DATABASE: ''
  MYSQL_ROOT_PASSWORD: ''

image:
  name: mysql
  tag: 5.7

service:
  type: ClusterIP
  port: 3306

autoscaling:
  enabled: false
  #  minReplicas: 1
  #  maxReplicas: 5
  #  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
