apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-nginx
  labels:
    app: {{ .Chart.Name }}-nginx
    environment: {{ .Values.metadata.labels.environment }}

spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.nginxReplicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-nginx
      environment: {{ .Values.metadata.labels.environment }}
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-nginx
        environment: {{ .Values.metadata.labels.environment }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-nginx
          image: "{{ .Values.image.repository }}/{{ .Values.nginx-image.name }}:{{ .Values.nginx-image.tag }}"
          resources: {}
          ports:
            - containerPort: {{ .Values.nginx-service.port }}
              protocol: TCP
      restartPolicy: Always

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-php
  labels:
    app: {{ .Chart.Name }}-php
    environment: {{ .Values.metadata.labels.environment }}

spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.phpReplicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-php
      environment: {{ .Values.metadata.labels.environment }}
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-php
        environment: {{ .Values.metadata.labels.environment }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-php
          image: "{{ .Values.image.repository }}/{{ .Values.php-image.name }}:{{ .Values.php-image.tag }}"
          resources: {}
          workingDir: /var/www/
      restartPolicy: Always
